### PR TITLE
Add reference to IXWebSocket library

### PR DESCRIPTION
**Pull request by bsergean**
Here are the results -> https://bsergean.github.io/IXWebSocket/autobahn/index.html

Thanks so much for writing this regression test, I did fix a [ton of bugs](https://github.com/machinezone/IXWebSocket/blob/master/docs/CHANGELOG.md) thanks to it.

I hope it will help me fixing an [odd zlib decompression bug](https://github.com/aaugustin/websockets/issues/665) in the websockets library which I'm using as my server this C++ library talks to.

### CODE REVIEW

**Comment by bsergean** [comment]
FYI 
C++ library is https://github.com/machinezone/IXWebSocket
The python service it talks to is https://github.com/machinezone/cobra

**Comment by oberstet** [comment]
thanks for the praise;) and using autobahn!

**Comment by bsergean** [comment]
Thanks for making autobahn !

ps:
I noticed that those links are broken from the README page -> https://crossbar.io/autobahn/testsuite/reports/clients/index.html

**Comment by oberstet** [comment]
re broken link: oh, thx for letting us know! (filed https://github.com/crossbario/crossbar/issues/1625)

**Pull request merged**
